qumbia/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :questions, :defaults => { :format => 'json' } do
    resources :answers, :defaults => { :format => 'json' } 
  end

  resources :answers, :defaults => { :format => 'json' } do 
      put :vote
      resources :votes, :defaults => { :format => 'json'}
  end

  root 'questions#index'

  post 'searches/index' => 'searches#index', as: 'searches'

  get 'searches/search_questions' => 'searches#search_questions', as: 'search_questions'

  get 'searches/search_answers' => 'searches#search_answers', as: 'search_answers'

end

qumbia/app/views/layouts/_search.html.erb
<div class="content">
	<%= form_tag searches_path do %>
	<input class="search full-width" id= "searchbar" name="query" placeholder="Search" type = "text" autocomplete="off">
	<% end %>
</div>

qumbia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ASK ALMA</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Lato:100,300,400,300italic' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<nav>
		<%= render :partial => 'layouts/search' %>

		<div class="content">
			<ul>
				<li class="action-item">
					<%= link_to(questions_path) do %>
					<p>ASK ALMA</p>
					<% end -%>
				</li>
				<li>
					<%= link_to(questions_path) do %>
					<p>newsfeed</p>
					<% end -%>
				</li>
				<li>
					<%= link_to(new_question_path) do %>
					<p>ask a question</p>
					<% end -%>
				</li>
			</ul>
			<ul class="right">
				<li>
					<% if user_signed_in? %>
  						<li>
  							<%= link_to('logout', destroy_user_session_path, :method => :delete) %>
  						</li>
					<% end %>
				</li>
				<li><a href="#"><p>help</p></a></li>
			</ul>
		</div>
	</nav>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<div class="jumbotron">
		<div class="content">
			<h1> Ask Alma </h1>
			<div>
				<h3> Quora for Columbia </h3>
			</div>
		</div>
	</div>


<%= yield %>

</body>

<footer>
	<div class="content">
		<p>Built by ADI's Qumbia Team!</p>
	</div>
</footer>
</html>

qumbia/app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ASK ALMA</title>
	<%= stylesheet_link_tag 'welcome' %>
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i" rel="stylesheet">
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="jumbotron">
		<div class="content">
			<h1><i>AskAlma</i></h1>
            
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        </div>

		<div class="sign-in-up">
			<ul class="tabs">
				<li class="tab active"><a href="#login">Log In</a></li>
				<li class="tab"><a href="#signup">Sign Up</a></li>
			</ul>

			<div class="tab-forms">
				<div id="login">
					<h3>Welcome back!</h3>
					<%= render "users/sessions/new" %>
					<%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
				</div>
				
				<div id="signup">
					<h3>Sign up with your Columbia email.</h3>
					<%= render "users/registrations/new" %>
				</div>
			</div>
		</div>
	</div>
</body>

<%= javascript_include_tag 'welcome' %>
</html>