qumbia/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :questions, :defaults => { :format => 'json' } do
    resources :answers, :defaults => { :format => 'json' } 
  end

  resources :answers, :defaults => { :format => 'json' } do 
      put :vote
      resources :votes, :defaults => { :format => 'json'}
  end

  root 'questions#index'

  post 'searches/index' => 'searches#index', as: 'searches'

  get 'searches/search_questions' => 'searches#search_questions', as: 'search_questions'

  get 'searches/search_answers' => 'searches#search_answers', as: 'search_answers'

end

qumbia/app/models/search.rb
class Search < ActiveRecord::Base
	
end

qumbia/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def index
		@q = "%#{params[:query]}%"
		@questions = Question.where("title LIKE ? or text LIKE ?", @q, @q)
		@answers = Answer.where("body LIKE ?", @q)
		@users = User.where("email LIKE ?", @q)
	end

	def search_questions
		@q = "%#{params[:query]}%"
		@questions = Question.where("title LIKE ? or text LIKE ?", @q, @q)
	end

	def search_answers
		@q = "%#{params[:query]}%"
		@answers = Answer.where("body LIKE?", @q)
	end

	def search_categories
		@q = "%#{params[:query]}%"
		@categories = Category.where("name LIKE?", @q)
	end

end

qumbia/app/views/searches/index.html.erb
<div class="search">

	<div class="content">

		<%=	link_to "See all questions", search_questions_path(:query=> @q) %>
		<% @questions[0..2].each do |question| %>
		<%= link_to(question) do %>
		  	<h3>Question: <%= question.title %></h3>
		  	<p>Description: <%= question.text %></p>
		<% end -%>
		<% end %>
	</div>

	<div class="content">
		<%=	link_to "See all answers", search_answers_path(:query=> @q) %>
		<% @answers[0..2].each do |answer| %>
		<%= link_to(answer.question) do %>
		  	<h3>Answer: <%= answer.body %></h3>
		<% end -%>
		<% end %>
	</div>

	<div class="content">
		<%=	link_to "See all categories", search_categories_path(:query=> @q) %>
		<% @categories[0..2].each do |category| %>
		<%= link_to(category) do %>
		  	<h3> <%= category.name %></h3>
		<% end -%>
		<% end %>
	</div>
</div>

qumbia/app/views/searches/search_answers.html.erb
<div class="search">

	<div class="content">
		<% @answers.each do |answer| %>
		<%= link_to(answer.question) do %>
		  	<h3>Answer: <%= answer.body %></h3>
		<% end -%>
		<% end %>
	</div>
		
</div>

qumbia/app/views/searches/search_categories.html.erb
<div class="search">

	<div class="content">
		<% @categories.each do |category| %>
		<%= link_to(category) do %>
		  	<h3><%= category.name %></h3>
		<% end -%>
		<% end %>
	</div>
		
</div>

qumbia/app/views/searches/search_questions.html.erb
<div class="search">

	<div class="content">
		
		
		<% @questions.each do |question| %>
		<%= link_to(question) do %>
		  	<h3>Question: <%= question.title %></h3>
		  	<p>Description: <%= question.text %></p>
		<% end -%>
		<% end %>
		
	</div>
</div>